# Generated by Django 6.0.2 on 2026-02-10 14:57

import sqlitetrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        sqlitetrigger.migrations.AddTrigger(
            model_name='book',
            trigger=sqlitetrigger.migrations.CompiledTrigger(drop_sql=['DROP TRIGGER IF EXISTS sqlitetrigger_example_book_sheets_update;'], install_sql=['CREATE TRIGGER sqlitetrigger_example_book_sheets_update\n    AFTER UPDATE ON example_book\n    FOR EACH ROW\nBEGIN\n    UPDATE example_book SET sheets = new.pages / 2 WHERE id = new.id;\nEND;'], name='sheets_update'),
        ),
    ]
